-- Extensions
create extension if not exists "uuid-ossp";

-- 1. Tenants (Restaurantes)
create table if not exists public.tenants (
  id uuid default uuid_generate_v4() primary key,
  name text not null,
  slug text unique not null,
  logo text,
  status text check (status in ('active', 'suspended')) default 'active',
  plan text check (plan in ('free', 'pro', 'enterprise')) default 'free',
  billing_status text check (billing_status in ('paid', 'pending', 'overdue')) default 'paid',
  due_date timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Users (Funcionários e Admins)
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  tenant_id uuid references public.tenants(id) on delete cascade,
  name text not null,
  email text not null,
  role text check (role in ('super_admin', 'tenant_admin', 'waiter', 'kitchen', 'courier', 'cashier', 'manager')) not null,
  status text check (status in ('active', 'inactive')) default 'active',
  avatar text,
  current_location jsonb,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Payment Integrations
create table if not exists public.payment_integrations (
  id uuid default uuid_generate_v4() primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  provider text check (provider in ('asaas', 'mercadopago', 'cielo', 'rede', 'pagarme', 'pagbank')) not null,
  api_key text,
  api_secret text,
  pix_key text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Support Tickets
create table if not exists public.support_tickets (
  id uuid default uuid_generate_v4() primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  subject text not null,
  description text not null,
  status text check (status in ('open', 'in_progress', 'resolved', 'closed')) default 'open',
  priority text check (priority in ('low', 'medium', 'high', 'urgent')) default 'medium',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Menu Items
create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  name text not null,
  description text,
  price decimal(10,2) not null,
  category text not null,
  image text,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Sold Items (Tokens/Tickets)
create table if not exists public.sold_items (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  code text not null,
  item_name text not null,
  item_id bigint references public.menu_items(id) on delete set null,
  price decimal(10,2) not null,
  status text check (status in ('valid', 'used')) default 'valid',
  type text check (type in ('token', 'ticket')) default 'token',
  order_id bigint,
  purchase_time timestamp with time zone default timezone('utc'::text, now()) not null,
  used_time timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on RLS for isolation
alter table public.tenants enable row level security;
alter table public.users enable row level security;
alter table public.payment_integrations enable row level security;
alter table public.support_tickets enable row level security;
alter table public.menu_items enable row level security;
alter table public.sold_items enable row level security;

-- Drop existing policies if they exist (to allow re-running script)
drop policy if exists "Tenants isolation" on public.tenants;
drop policy if exists "SuperAdmins view all tenants" on public.tenants;
drop policy if exists "Users tenant isolation" on public.users;
drop policy if exists "SuperAdmins view all users" on public.users;
drop policy if exists "Menu tenant isolation" on public.menu_items;
drop policy if exists "SoldItems tenant isolation" on public.sold_items;

-- Super Admin can see EVERYTHING
create policy "SuperAdmins view all tenants" on public.tenants for all 
using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') );

create policy "SuperAdmins view all users" on public.users for all 
using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') );

-- Tenant users can only see their own Tenant and data
create policy "Tenants isolation" on public.tenants for all
using ( id = (select tenant_id from public.users where id = auth.uid()) );

create policy "Users tenant isolation" on public.users for all
using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "Menu tenant isolation" on public.menu_items for all
using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SoldItems tenant isolation" on public.sold_items for all
using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );


-- Insert Test Data (if empty)
do $$
declare
  super_admin_id uuid := '00000000-0000-0000-0000-000000000001';
  test_tenant_id uuid := '11111111-1111-1111-1111-111111111111';
  tenant_admin_id uuid := '22222222-2222-2222-2222-222222222222';
  waiter_id uuid := '33333333-3333-3333-3333-333333333333';
begin
  
  -- Create Tenant
  insert into public.tenants (id, name, slug, plan)
  values (test_tenant_id, 'Restaurante Teste', 'teste', 'pro')
  on conflict (id) do nothing;

  -- Create Users in auth.users
  insert into auth.users (id, instance_id, email, encrypted_password, email_confirmed_at, created_at, updated_at)
  values 
  (super_admin_id, '00000000-0000-0000-0000-000000000000', 'superadmin@woobar.com', crypt('123456', gen_salt('bf')), now(), now(), now()),
  (tenant_admin_id, '00000000-0000-0000-0000-000000000000', 'dono@bar.com', crypt('123456', gen_salt('bf')), now(), now(), now()),
  (waiter_id, '00000000-0000-0000-0000-000000000000', 'garcom@bar.com', crypt('123456', gen_salt('bf')), now(), now(), now())
  on conflict (id) do nothing;
  
  -- Insert them into public.users
  insert into public.users (id, tenant_id, name, email, role)
  values
  (super_admin_id, null, 'Super Administrador', 'superadmin@woobar.com', 'super_admin'),
  (tenant_admin_id, test_tenant_id, 'Dono do Bar', 'dono@bar.com', 'tenant_admin'),
  (waiter_id, test_tenant_id, 'Garçom Mobile', 'garcom@bar.com', 'waiter')
  on conflict (id) do nothing;

  -- Insert some test menu items
  insert into public.menu_items (tenant_id, name, description, price, category, image)
  values
  (test_tenant_id, 'Classic Burger', 'Pão, carne e queijo', 32.90, 'Burgers', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80'),
  (test_tenant_id, 'Fritas Especial', 'Cheddar e bacon', 45.00, 'Porções', 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=800&q=80')
  on conflict do nothing;

end $$;
