-- Woobar Multi-tenant feature tables
-- Adds the domain feature tables (categories, orders, cover_charge_transactions,
-- tables, events, courier_positions, chat_messages) in multi-tenant style with
-- tenant_id + tenant-scoped RLS. Mirrors the block appended to schema.sql.
-- Idempotent: safe to re-run.

-- Categories (por tenant)
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  name text not null,
  display_order integer default 0,
  unique (tenant_id, name)
);

-- Orders (delivery)
create table if not exists public.orders (
  id text primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  customer text not null,
  customer_phone text,
  items jsonb not null,
  total decimal(10,2) not null,
  status text check (status in ('pending', 'preparing', 'ready', 'delivering', 'delivered', 'cancelled')) default 'pending',
  time text,
  address text,
  location jsonb,
  courier_id uuid references public.users(id) on delete set null,
  payment_method text,
  notes text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

-- Cover charge transactions
create table if not exists public.cover_charge_transactions (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  type text check (type in ('entry', 'exit')) not null,
  amount decimal(10,2) not null,
  method text check (method in ('pix', 'credit', 'debit', 'cash')) not null,
  timestamp timestamptz not null default timezone('utc'::text, now())
);

-- Restaurant tables
create table if not exists public.tables (
  id integer not null,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  name text not null,
  seats integer not null,
  status text check (status in ('free', 'occupied', 'reserved', 'dirty')) default 'free',
  orders jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  primary key (tenant_id, id)
);

-- Events
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  title text not null,
  date text not null,
  time text not null,
  location text,
  image text,
  tickets jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

-- Courier positions
create table if not exists public.courier_positions (
  courier_id uuid primary key references public.users(id) on delete cascade,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  lat numeric(10,6) not null,
  lng numeric(10,6) not null,
  timestamp timestamptz not null default timezone('utc'::text, now())
);

-- Chat messages
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  order_id text references public.orders(id) on delete cascade,
  sender text check (sender in ('customer', 'system')) not null,
  message text not null,
  timestamp timestamptz not null default timezone('utc'::text, now())
);

-- Turn on RLS for feature tables
alter table public.categories enable row level security;
alter table public.orders enable row level security;
alter table public.cover_charge_transactions enable row level security;
alter table public.tables enable row level security;
alter table public.events enable row level security;
alter table public.courier_positions enable row level security;
alter table public.chat_messages enable row level security;

-- Drop existing policies if they exist (to allow re-running script)
drop policy if exists "SuperAdmins manage categories" on public.categories;
drop policy if exists "Categories tenant isolation" on public.categories;
drop policy if exists "SuperAdmins manage orders" on public.orders;
drop policy if exists "Orders tenant isolation" on public.orders;
drop policy if exists "SuperAdmins manage cover charge" on public.cover_charge_transactions;
drop policy if exists "Cover charge tenant isolation" on public.cover_charge_transactions;
drop policy if exists "SuperAdmins manage tables" on public.tables;
drop policy if exists "Tables tenant isolation" on public.tables;
drop policy if exists "SuperAdmins manage events" on public.events;
drop policy if exists "Events tenant isolation" on public.events;
drop policy if exists "SuperAdmins manage courier positions" on public.courier_positions;
drop policy if exists "Courier positions tenant isolation" on public.courier_positions;
drop policy if exists "SuperAdmins manage chat messages" on public.chat_messages;
drop policy if exists "Chat messages tenant isolation" on public.chat_messages;

-- Feature tables: super_admin (global) + tenant-scoped access
create policy "SuperAdmins manage categories" on public.categories for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Categories tenant isolation" on public.categories for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SuperAdmins manage orders" on public.orders for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Orders tenant isolation" on public.orders for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SuperAdmins manage cover charge" on public.cover_charge_transactions for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Cover charge tenant isolation" on public.cover_charge_transactions for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SuperAdmins manage tables" on public.tables for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Tables tenant isolation" on public.tables for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SuperAdmins manage events" on public.events for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Events tenant isolation" on public.events for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SuperAdmins manage courier positions" on public.courier_positions for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Courier positions tenant isolation" on public.courier_positions for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

create policy "SuperAdmins manage chat messages" on public.chat_messages for all
  using ( exists (select 1 from public.users where id = auth.uid() and role = 'super_admin') )
  with check ( true );

create policy "Chat messages tenant isolation" on public.chat_messages for all
  using ( tenant_id = (select tenant_id from public.users where id = auth.uid()) )
  with check ( tenant_id = (select tenant_id from public.users where id = auth.uid()) );

-- Indexes for feature tables
create index if not exists idx_orders_tenant_status on public.orders(tenant_id, status);
create index if not exists idx_orders_tenant_courier on public.orders(tenant_id, courier_id);
create index if not exists idx_cover_charge_tenant_timestamp on public.cover_charge_transactions(tenant_id, timestamp);
create index if not exists idx_events_tenant_date on public.events(tenant_id, date);
create index if not exists idx_chat_messages_tenant_order on public.chat_messages(tenant_id, order_id);

-- Seed categories and tables for the test tenant
insert into public.categories (tenant_id, name, display_order)
values
  ('11111111-1111-1111-1111-111111111111', 'Burgers', 1),
  ('11111111-1111-1111-1111-111111111111', 'Porções', 2),
  ('11111111-1111-1111-1111-111111111111', 'Bebidas', 3),
  ('11111111-1111-1111-1111-111111111111', 'Drinks', 4)
on conflict (tenant_id, name) do nothing;

insert into public.tables (id, tenant_id, name, seats, status)
select g, '11111111-1111-1111-1111-111111111111', 'Mesa ' || g, case when g % 2 = 0 then 6 else 4 end, 'free'
from generate_series(1, 16) as g
on conflict (tenant_id, id) do nothing;